baseurl = "http://explicable.ml/"
languageCode = "en-US"
title = "Explicable.ML"
theme = "hugo-assembly"

# Metadata
[params]
  author = "Benoît Paris"
  description = "Explicable Machine Learning"
  #github = "https://github.com/benoitparis"
  #copyright = "Benoît Paris Consulting"
  #copyright_link = "http://benoit.paris"

# banner section (from here on is for assembly theme)
[params.banner]
  title = "Welcome to your data"
  byline = "Rediscover it. Explore its topology. Find subtle yet invaluable signals."
  
[params.actions] # CTAs
  enable = true
  register = "CTA Now!"

# Navigation section
[params.nav]
  home = "Home"
  services = "Services"
  welcome = "Welcome"
  contact = "Contact Us"


# Services section
[params.services]
  enable = true
  title = "Services"
  #subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit."
  
  [[params.services.item]]
    weight = "A"
    description = "We use algorithms that win competitions, we just open them and present how they take their decisions."
    button_item_info = "Performant"

  [[params.services.item]]
    weight = "B"
    description = "Know exactly how your models work. Establish compliance easily"
    button_item_info = "Transparent"
    
  [[params.services.item]]
    weight = "C"
    description = "Gain deep insights about the topology of your clients, at an intuitive glance"
    button_item_info = "Visual"
    
  [[params.services.item]]
    weight = "A"
    description = "Fully fledged data management, Extract-Transform-Load &amp; Machine Learning environment working together"
    button_item_info = "Agile"

  [[params.services.item]]
    weight = "B"
    description = "Follow the driving signals in the data as a management principle, concentrate only on data that has value"
    button_item_info = "Smart"

  [[params.services.item]]
    weight = "C"
    description = "Join open datasets with your data, and enable further insights and performance"
    button_item_info = "Enriched"

# Welcome section
[params.welcome]
  enable = true
  title = "Explicable Machine Learning"
  subtitle = "Explore the hidden signals in your data"
  description = "Gain invaluable insights from your existing databases that you would have otherwise missed with regular machine learning. Use state-of-the-art predictive algorithms that we make open and inspectable to you. Discover implicit structures and how they relate to events like customers buying your product."
  button_text = "Contact Us Now"

# Contact section
[params.contact]
  enable = true
#   title = "Get In Touch"
#   message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#   name_placeholder = "Your name"
#   email_placeholder = "Your email"
#   email_disclaimer = "We'll never share your email with anyone else."
#   message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  copy = "2017-2019 &copy; [Benoît Paris Consulting](http://benoit.paris) | All rights reserved"
  twitter = ""
  facebook = ""
  instagram = ""
