baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Benoît Paris"
theme = "hyde"


[params]
    github = "https://github.com/benoitparis"

[Author]
    name = "Benoît Paris"

