baseurl = "http://explicable.ml/"
languageCode = "en-us"
title = "Explainable Machine Learning"
theme = "hyde"


[params]
    github = "https://github.com/benoitparis"
    copyright = "Benoît Paris Consulting"
    copyright_link = "http://benoit.paris"

[Author]
    name = "Benoît Paris"
